### ISSUE TITLE
Event Registry Interface

### ISSUE THREAD

**Issue by MorganNesbitt** [zcmoore/plpTool-prototype#10]

**Comment by zcmoore** [comment]
Complete. See [edu.asu.plp.tool.backend.EventRegistry](https://github.com/zcmoore/plpTool-prototype/blob/master/src/edu/asu/plp/tool/backend/EventRegistry.java)
Abstraction to an interface was deemed unnecessary, on account of overabstraction (a single, static access point is ideal in this situation).
