### ISSUE TITLE
BiDirectional Data Structure

### ISSUE THREAD

**Issue by MorganNesbitt** [zcmoore/plpTool-prototype#13]

**Comment by zcmoore** [comment]
Completed.
See [edu.asu.plp.tool.backend.OrderedBiDirectionalOneToManyHashMap](https://github.com/zcmoore/plpTool-prototype/blob/master/src/edu/asu/plp/tool/backend/OrderedBiDirectionalOneToManyHashMap.java) and [edu.asu.plp.tool.backend.OrderedBiDirectionalOneToManyHashMap](https://github.com/zcmoore/plpTool-prototype/blob/master/src/edu/asu/plp/tool/backend/OrderedBiDirectionalOneToManyHashMap.java)
